server.port=9203
spring.application.name=transaction-service

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=banking_transaction_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=test
spring.datasource.password=test123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.topic.transaction=transaction-topic

